# Docker image version
image-version: 2.6.0
fb-rje:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:gBTbxc+PzV29/1v5JhY=,iv:LKqYYrGC0zal0FXz5uFBwNuxIEhksnapUlFPsxxjeTM=,tag:au1OosGtoOdG+gZ9YXYzaA==,type:str]
        hostname: ENC[AES256_GCM,data:u5Wp7ShUH7MeTQqx,iv:zlDe+HZw43OLo298lz7qvbcRIVEX/SC4r8/NTz2Q934=,tag:gWqBubZS6Cz8/yBQa39QRg==,type:str]
        username: ENC[AES256_GCM,data:A9w+D2P0pbmiRA==,iv:y23tswjc7Sm2aoNSv3PytU5MHC+zDL0ruVQC8YQU+28=,tag:rE+J6c2H6hxNKhwQsH4N9w==,type:str]
        password: ENC[AES256_GCM,data:lkRFGY88zzscqwqyfE375+PB/2oyqcnTI8cYr4RsZE4=,iv:PBe2icakXL6u2i3lcTzcXNiJ4wDn9GDpXQJhimAl6o4=,tag:+ehgEFNQUlV1CCTTgpekvQ==,type:str]
      # sops:enc
      - name: ENC[AES256_GCM,data:CJE5XPooKuIgm0pvDqhIp00=,iv:kwVmTbJyjXhadGt2VfDaBGjDNQPReCC5/sD9mlyKZC4=,tag:zCEct4CncWA7vnJhql1bUQ==,type:str]
        hostname: ENC[AES256_GCM,data:FRytzJ4znvY1g2/u,iv:h2vR/rXGx2xgO3jpEiZpRpou8naQnxhM07Bpq5ScgBA=,tag:mv3rX5gMkGsqoEC1+exyCg==,type:str]
        username: ENC[AES256_GCM,data:nebt+A==,iv:w0EF+PmAP+ML9cLsBNklMD9tb5Jryc40U1iC+qN0wfA=,tag:wv6jAB0FwlFkbobrDZwcOA==,type:str]
        password: ENC[AES256_GCM,data:6AVDVfKoNId/HGee9vigGA==,iv:w0PHKPtecPnmtnVacCWXJWVHOOaYL7f8tSCzizwOj9Y=,tag:nb1m2r6koOyla4iFG1dEvQ==,type:str]
fb-drs:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:C/PK7MEFH3Xs8i7WuIs=,iv:hHHqIGGavGuWgxXXn6kVVGoTX9dT1ViPVIJapMNpmV0=,tag:shlf58hKNEQ9k44279qlog==,type:str]
        hostname: ENC[AES256_GCM,data:Xfuv//AY2VhI6TXO,iv:ZNZc/8+Bw+9WpFPJEz+EI8FNi76Juie+c4OjZCC/2/4=,tag:B0rsx+jdi09vXl5FsR35jA==,type:str]
        username: ENC[AES256_GCM,data:w2DuE2PFcehElA==,iv:OLKTZgYlw/j3JjySmhDDhRXKJHECKGcdkgIxEP3UC7I=,tag:dm0kJZXvezJ8pzMBGso8JQ==,type:str]
        password: ENC[AES256_GCM,data:2Pey+cjDpzohIKnMowrDAgV9u6J4+pxkGvGs5f39mQc=,iv:NR4qFAHCcxSI3g1hbpKLUQ+zMHNDgPYSIuf1/oH9pfw=,tag:AtcRJUR1FxxlYKMCugl2QQ==,type:str]
sops:
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOG14YXJXNEZGMTBheUlW
        TURRWTZiQ3JBbDY5SWcwZjVlUkZ6Nk1nS1NFCm5qREdlNUlhQVJyY0JqZWpUN0Fq
        WGE3NlVhVVdzTU5LRThVU2xjRFdZSXcKLS0tIGxhSjRDN2VYdXVmTzQ5SyttcDlN
        VE0yUHJJdnU0eDkwVHNiRWRNd0paZFkKovNGUkKMxdHRENS5Ds3KKenlDnfenx8b
        rqwlSBrvlASEjeu+Tc/764ibPjrTWhhgWueYYuQXkpeZQamtlr8gyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T09:21:23Z"
  mac: ENC[AES256_GCM,data:ioFlHyUXy3QAaH1pc9Re6w36DJIlpUhfBiLQirdA64IC5Euy0CBZ0uonyoOzcoIm6yw72oAQgN6lRVRe+JNLDEIX9NbLpy+5egKR3HDTttCDC5Ur4tmLhjNCqF+ybb9nvvDjyzWzHd+pBrCX7TmBMW34+E3D20ZG/UTDSyvDjsA=,iv:fVCguq0JI5DvCJGopZicKZSS9y1kel4bneKSYB9EdrM=,tag:Ba0yodEBBb49NdwYJEKF8g==,type:str]
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.11.0
