# Docker image version
image-version: 2.6.0
fb-rje:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:kaH6G4s6XmB2pVY1zvo=,iv:FPNUDYUpefLTtMS8+tYv0ewRBULW28rlvfD16M7TMdQ=,tag:Oyg+u6OD8GHxQsQFijYg3Q==,type:str]
        hostname: ENC[AES256_GCM,data:ZDX7wnLj0jqJfCic,iv:ENVZh4CkQMPdvvykUTzQ41z+88/X52/I5hAPGY84yw4=,tag:39tS0oMZoEs5tHpk5Uo+Rw==,type:str]
        username: ENC[AES256_GCM,data:hHJisThPRkDkkA==,iv:Dt9k6bAHNUQ8W7ojP6dNjlQRWXAYZZBVRLDWK6MLX+4=,tag:c6jR21fpKcrX0LktxECu4Q==,type:str]
        password: ENC[AES256_GCM,data:rBTViU/SfSjN9d6ZPbIb6LNlb5KYUqiiFKpk7FZskSc=,iv:oCD4AAjIMqJvrgVkcunYzoC34eVvjDEZoCRYwNl2hgA=,tag:rQc1rH1mrg10ROdXWmuzrA==,type:str]
    # sops:enc
    #ENC[AES256_GCM,data:zMkN0DEzoGv0LCEqCQIO/a+q8ZpUF3gKqQ==,iv:kTspHjW+qQD2k7++Zi1r/IpDezEhOiLecgmHE7H+1FM=,tag:Iaki8UKb/JV455ygZwe2gw==,type:comment]
    #ENC[AES256_GCM,data:4OpNx71dtsXSO9Q5kpmWlab+H/MYXKix,iv:W8WG4DgfMgjlXeKqx6Mn1Zwgr4+NUOu/od3J6aXJauc=,tag:AXTIVC/6xB1nmWQxkASb2A==,type:comment]
    #ENC[AES256_GCM,data:yMchIxUlAO94NhrWuDFtaY8=,iv:Nz/s6VCRoT9vgj061yQvbDCAI+cpjMluKupnz7dWtD0=,tag:vvLzTy+FKFH0179EU3lOoA==,type:comment]
    #ENC[AES256_GCM,data:Si96a6xaoI3RraCjs96bGGrHDXPtHswOKMBnmw==,iv:oqeT7FWG0h70kZzqTvqTktbrStjHPtAyJzQNHOoG6Jk=,tag:t3TvuXmuQCXEBKyKqlSJoA==,type:comment]
fb-drs:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:wr9EU32oliVKw6qNcSA=,iv:6nXyygHbECziMcnVcDGbeYPsOG9jSV4BkiCjhBl30uc=,tag:gh7cdXUIVfYGa/eb0/KQLA==,type:str]
        hostname: ENC[AES256_GCM,data:RyBS6Y389biEKxLL,iv:TjCrQS6SUfJ7rvIsF7urqtJ0Wejm7kJMSIdCFTY7p28=,tag:kp1jszlLIw4AsQ51YlPP3A==,type:str]
        username: ENC[AES256_GCM,data:x7UI/0j2WrAvIA==,iv:1/2UCkKbMKqt6vUSfF6dQJpH9QykzpTE68UPyHjayaw=,tag:D0sUZtsvt1VC2NmbyrmrSg==,type:str]
        password: ENC[AES256_GCM,data:gqXY+qB9gZxVZ0tWVxSmuo7TlUfjELzpifJFoxJpx2g=,iv:ECpoeA8SVyuQFn4TAYZXtysMWDQSTGPhBDjjAcZ9Nb8=,tag:Rixn9BgKcucgKidz6yrNvQ==,type:str]
sops:
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z1BTOWxoS3U2TDNWRHlm
        MGFvZE00bGxYSDQ0a0czWVAyd0NVSjFncXlZCnFsR1p1Yk15SnRTT0UxcU9nWTI4
        ZG51L0VKblRKaDRvZnhqZzVyUzQ0WjQKLS0tIHZycWxkdWJvOExtbGJ3OXVQK1ZO
        NGRmMTFzVFBLWnNURDlNWVVLOXZyRlkKGed0r4Pj7E06+xRp5Utn6quMPeBCondm
        lppfjpXipGpQH5Ks6D/Mc9lwgrtfz4yG1iPE1IlFWVViFfGnK/qBeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T09:26:44Z"
  mac: ENC[AES256_GCM,data:4+8m6UcrYjWi/mGk4uaY5LRdJ4zqXNAP1KXJkTexGB/Lxpwa9h+KRXTBvgSoq2vZs4ecSErBvFw1Szuif1BYnVkZDzxx6ihMDiH6q1pzd45Ju82+Vch2c9TCE+zvko/AloIRT9MpN8HC27IaiZ6ohe8r9A33IQ1O4c1NFqh2mCY=,iv:/8/+v7ImCoQuAYr0KWxceWfUF5sCbQno9v8QC15iKDU=,tag:inR6N4eh4Xtt/Hx6d/TehQ==,type:str]
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.11.0
