# Common credentials
# sops:enc
credentials:
  username: ENC[AES256_GCM,data:d61p+fvzz+fXDA==,iv:cEKEt8WH4sRnEfPkc2046rkzPI0fAmN/egD77jAwPU8=,tag:mtq8Xh7CbuHF+6gFj3jO6w==,type:str]
  password: ENC[AES256_GCM,data:mTzhj5NDYKV0YibQkegcTgvhMIsNOU9t+rr8gxY1ecg=,iv:C9v3oanJLXW6rVH12eqgmDeiTf5HNWnMq12hvJ/f6fI=,tag:LVMfGCu54smat87kcJG5mQ==,type:str]
# Docker image version
image-version: 2.6.0
fb-rje:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:GYKXiJjgljKPtzFaQYU=,iv:ELY3VQ7xDS6wUj+k80cSF6WY6O6teZRcy8aWTYwXOKo=,tag:HOi8hwaBtpbEsh3XKOMJlg==,type:str]
        hostname: ENC[AES256_GCM,data:I7ZKW2/DbDra5zzE,iv:i6H28Wf6f0mxE/IwwmhLFpSwVmhxTkhfEpy2AcRidH4=,tag:nP0dA27Ke2d9DghgHdjbzw==,type:str]
        !!merge <<:
          username: ENC[AES256_GCM,data:fASMvBliSQ1Opg==,iv:J3Uj72qisnZZdNgj7fjkLntqP6BmLGF07D0MAVKdDr4=,tag:/pKmZbwEAZp4RvOxTwUWtA==,type:str]
          password: ENC[AES256_GCM,data:Raa7T38067mzJnpryz4Xqkt5EwAsybclQIRopIYfbmk=,iv:U+Edncm7VJDHcA2CLXcx3Pm1N+bSQBx3pmY8PE5nya8=,tag:4Ys+G8qmvuvcY2+3SYDuxA==,type:str]
      # sops:enc
      - name: ENC[AES256_GCM,data:ZokirW/nvrE1ktAEqWZZol4=,iv:Ps9jhPhdWnvEeKt1/am44cHJN2WK549VnpjDphjK5OM=,tag:/9GezL0buJJ7VNDP0eTEcg==,type:str]
        hostname: ENC[AES256_GCM,data:CZMHcjFdtJ75GhAf,iv:8H32lL4GaUVCAhbyW2WOW4Q8XIaGkYXKEhMV8pWa/4k=,tag:eh8vpN/DIaCQcESMixa2Hw==,type:str]
        #ENC[AES256_GCM,data:L5KYcUG+gniqRfrluXGi3qI8Aag=,iv:Kj4hxS1n/4KgDjgMwuKfpBAYQOI4LxVjV/hIfbi0cnA=,tag:UIFxFj8u27YmUPdOn2sU+w==,type:comment]
        password: ENC[AES256_GCM,data:B4U7BfvEw8xL4G4ReM+yKQ==,iv:Ijxqzofuea/0QFTf2RwxcWtcRMXsTxv2C6ahyl88f3g=,tag:FitHO+268eE4L/9BO4iSug==,type:str]
fb-drs:
  image:
    tag: 2.6.0
  config:
    devices:
      # sops:enc
      - name: ENC[AES256_GCM,data:jlkyEPYbICOKPID/UhY=,iv:qHvSyfYUL4f8EMRgdPrdMYvW+fXLiuGE1NRYxqKLXmE=,tag:aXc/VzQKrBu3nI/Y7/tvvA==,type:str]
        hostname: ENC[AES256_GCM,data:DISlYGOirepGTQjI,iv:OSSgTT07mvzH8/yUbiVFUyXS2uegnF9mRqSnhj2Qscs=,tag:mPGk7miUGGpzZIh4Y66juQ==,type:str]
        !!merge <<:
          username: ENC[AES256_GCM,data:7a2M7uebxKLTHQ==,iv:0DPR4sJhVCnKvW5vPthonzW8d7xcXB8lg1dxf3uec8o=,tag:2QKLwm44o0e2mnI1nfelvw==,type:str]
          password: ENC[AES256_GCM,data:VgkoiLJBLWqMk3/ilg6ipIYw4+l5RSFhXYjWmNQZD9c=,iv:AfJ2zDR9Yjr4FC6Vh6GSt2HLljSQXaSequOtTZKNPpE=,tag:ylj4ZLC7jN0SrFgdS/Uqfg==,type:str]
sops:
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV2lXL0libjBDeGVVdEJG
        TEcyQTFSbThKRG5RNVBjNUlRam10b1l6VmtFCitiaU9NaEppcTdjbUZiNUlid1lZ
        bnptR2ZWQ3J5RlZ1UHVaQll0TVNjZm8KLS0tIE94U3hkSmMrVUpwdk0raWZPZUp6
        RTNuRDZqTExNK1lqQ09HMzhFMEw3RW8KI40yZqHcRZTrp4K+kB/ZQfeCmZCLJK1S
        56ywREtAFoViTlEOJw0CsAPY2WkN+uI9I/3S/a1/FAJy3tsCHDc5eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T09:16:13Z"
  mac: ENC[AES256_GCM,data:sId/u01P1pyOlCK9KHWa0NeKO1hLq7HlfY+kgwG9OrhygSGDb8pTbVV0pjkRZWoqEfxRuSKNTJGr0w3GW01nPqGfAwUi+pVazW9X4iA9ItTmf6+9l+cBFuzQgmkq++56bDCFuF6xT5pd+iTHVdSA19rRBW10Cft0rmHNJGmTVTc=,iv:QllLYTVQA6c9b2a07nZebHIdwmkuICQjbXotSJwaBR8=,tag:wIJUsnJfwMPH+AuadufSvQ==,type:str]
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.11.0
